import { Inter } from "next/font/google";
import "./globals.css";
 
const inter = Inter({ subsets: ["latin"] });
    import { formatInTimeZone } from 'date-fns-tz';
    export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="flex-">
         
        </div>
        {children}
      </body>
      
    </html>
  );
}
